In [1]:
import numpy as np

다음과 같은 과일 판매량 데이터가 있습니다. 각 과일의 1분기와 2분기 판매량이 주어졌을 때, NumPy 배열을 사용하여 아래 문제를 해결하세요.

1. 1분기와 2분기의 과일별 총 판매량을 구하세요.
2. 과일별 평균 판매량을 구하세요.

- **데이터**:
    - 1분기 판매량: `[200, 340, 150, 400]` (사과, 배, 오렌지, 바나나)
    - 2분기 판매량: `[220, 300, 180, 420]` (사과, 배, 오렌지, 바나나)

In [ ]:
arr1 = np.array([200, 340, 150, 400])
arr2 = np.array([220, 300, 180, 420])
print(np.add(arr1, arr2))

[420 640 330 820]


In [4]:
a = np.array([[1],
              [2],
              [3]])  # shape (3,1)
b = np.array([10, 20, 30])  # shape (3,)
a + b
# shape (3,3) 결과 생성


array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

### 브로드캐스팅
- 크기가 1인 축은 자동반복되어 큰 배열의 크기에 맞춰짐
- 두 배열 row 또는 col이 일치해야 함
- 자동확장이 직관적이지 않을 경우, shape을 꼭 확인

### 행렬 곱셈
- Dot Product / 내적
   - (2, 3) . (3, 10)처럼 1st 행렬의 열 수와 2st 행렬의 행 수가 같아야 함
   - 연산결과의 shape은 (1st 행렬의 행수, 2st 행렬의 열수)

In [ ]:
# (100, 20000) . (20000, 100)의 shape = (100, 100)
# (20000, 100) (100, 20000)의 shape = (20000, 20000)
# (100, 20000) (100, 20000)는 내적이 안됨.

---
### 연산 함수 및 집계 함수

In [13]:
arr_negative = np.array([[-1, -2], [-100, -200]])
arr_float = np.array([[1.234, -5.678], [-7.89, 10.123]])
arr = np.arange(1, 7).reshape(2, 3)

내림과 버림은 음수에서 좀 다르게 쓰임. 내림은 더 작은 수로 내리고 버림은 아예 버림
예: 내림은 -5.1 -> -6, 버림은 -5.1 -> -5

In [ ]:
# 내림
print(np.floor(arr_float), end='\n\n')

# 버림
print(np.trunc(arr_float))

[[ 1. -6.]
 [-8. 10.]]

[[ 1. -5.]
 [-7. 10.]]


최대/최소

In [18]:
arr = np.arange(1, 7).reshape(2, 3)

print(arr, end='\n\n')
print(np.max(arr))
print(np.min(arr), end='\n\n')

print(np.max(arr, axis=0))
print(np.max(arr, axis=1), end='\n\n')


print(np.min(arr, axis=0)) # 행 기준
print(np.min(arr, axis=1)) # 열 기준

[[1 2 3]
 [4 5 6]]

6
1

[4 5 6]
[3 6]

[1 2 3]
[1 4]


In [21]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])