In [1]:
import numpy as np

### ndarray 병합 및 분할

##### ndarray 요소 추가 및 삭제
- ndarray는 C++처럼 고정 길이 배열이므로 크기변경 불가 -> 변수에 재할당해서 append나 insert 가능

In [2]:
arr = np.array([1, 2, 3])
arr = np.append(arr, 4) # 재할당으로


In [10]:
arr = np.arange(1, 13).reshape(3, 4)
print(arr)

# arr는 2차원 배열이나 insert하니 1차원이 됨
print(np.insert(arr, 1, 100)) # i = 1에 100 insert하기

print(np.append(arr, 40))
print(np.append(arr, [[500, 600, 700, 800]], axis=0))
print(np.append(arr, [[100], [200], [300]], axis=1))


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[  1 100   2   3   4   5   6   7   8   9  10  11  12]
[ 1  2  3  4  5  6  7  8  9 10 11 12 40]
[[  1   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]
 [500 600 700 800]]
[[  1   2   3   4 100]
 [  5   6   7   8 200]
 [  9  10  11  12 300]]


In [ ]:
# np.delete()
arr = np.arange(1, 10)
print(arr)

# 마지막 인덱스 제거 (ndarray는 재할당해야 함)
arr = np.delete(arr, -1)
print(arr)

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8]


In [20]:
# 2차원에서 delete()
arr = np.arange(1, 11).reshape(2, 5)
print(arr, end='\n\n')

print(np.delete(arr, 1), end='\n\n')
print(np.delete(arr, 1, axis=0), end='\n\n')
print(np.delete(arr, 1, axis=1), end='\n\n')


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[ 1  3  4  5  6  7  8  9 10]

[[1 2 3 4 5]]

[[ 1  3  4  5]
 [ 6  8  9 10]]



--- ndarray 병합
- np.append()
- np. vstack()
- np.hstack()
- np.concatenate()

In [21]:
arr1 = np.arange(1, 13).reshape(3, 4)
arr2 = np.arange(13, 25).reshape(3, 4)
arr1, arr2

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]))

In [30]:
# np.append()
print(np.append(arr1, arr2), end='\n\n')
print(np.append(arr1, arr2, axis=0), end='\n\n')
print(np.append(arr1, arr2, axis=1), end="\n\n")

# np. vstack()
# vstack과 hstack은 병합할 대상을 튜플/리스트로 묶어서 전달해야 함
print(np.vstack([arr1, arr2]), end="\n\n")

# np.hstack()
print(np.hstack([arr1, arr2]), end="\n\n")

# np.concatenate()
print(np.concatenate([arr1, arr2], axis=None))
print(np.concatenate([arr1, arr2], axis=1), end="\n\n")

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

[[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

[[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]]



In [39]:
# np.split()
arr = np.hstack([arr1, arr2])
print(arr, end="\n\n")

print(arr, end='\n\n')
print(np.split(arr, 2, axis=1))

[[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]]

[[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]]

[array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]]), array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])]
