In [3]:
import numpy as np

### ndarray 형태 변경

In [14]:
# reshape()

arr = np.arange(12)
print(arr.ndim)

arr = arr.reshape(3, 4)
print(arr.ndim, arr.shape, "\n")

arr = arr.reshape(6, 2)
print(arr.ndim, arr.shape, "\n")

# [ ] 껍데기가 있어서 (1, 12) shape이지만 2차원임
arr = arr.reshape(1, 12)
print(arr)
print(arr.ndim, arr.shape, "\n")

print(arr.reshape(-1), "\n") # 한 차원 낮춤

print(arr.reshape(4, -1), "\n") # 자동

1
2 (3, 4) 

2 (6, 2) 

[[ 0  1  2  3  4  5  6  7  8  9 10 11]]
2 (1, 12) 

[ 0  1  2  3  4  5  6  7  8  9 10 11] 

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 



In [22]:
arr = np.arange(50).reshape(5, -1)
print(arr, "\n")

# np.ravel(): 1차원으로 변환
print(np.ravel(arr), "\n")

# np.expand_dims(): 차원을 1늘림
arr_1d = np.arange(10)
print(arr_1d.shape, arr_1d)
print(np.expand_dims(arr_1d, axis=1))
print(np.expand_dims(arr_1d, axis=1).shape)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]] 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49] 

(10,) [0 1 2 3 4 5 6 7 8 9]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(10, 1)


In [37]:
# np.sqeeze(): 요소가 한개인 차원을 제거
arr = np.array([[1, 2]])
print(arr, arr.shape)
arr1 = np.squeeze(arr)
print(arr1, arr1.shape, '\n')

arr = np.array([[[[1], [2]]],[[[3], [4]]]])
print(arr, arr.shape)
arr1 = np.squeeze(arr)
print(arr1, arr1.shape)

[[1 2]] (1, 2)
[1 2] (2,) 

[[[[1]
   [2]]]


 [[[3]
   [4]]]] (2, 1, 2, 1)
[[1 2]
 [3 4]] (2, 2)
