# 출력층 설계 (Output layer)

In [7]:
import numpy as np

# np.exp(1000) 이것만 해도 오버플로우나서 max로 빼야함
def softmax(z):
    exp_z = np.exp(z - np.max(z))
    return exp_z / np.sum(exp_z)

x = np.array([1000, 1001, 800])
print(softmax(x))

[2.68941421e-01 7.31058579e-01 3.72187099e-88]


- PyTorch 라이브러리 함수 사용

In [8]:
import torch
import torch.nn.functional as F


# x = torch.tensor([1000, 1001, 1002], dtype=torch.float32)
x = np.array([1000, 1001, 1002], dtype=float)
x = torch.from_numpy(x)

# softmax 를 쓰려면 float(실수) 이어야 함
softmax_output = F.softmax(x, dim=0)
print(softmax_output)

print(torch.sigmoid(x))

tensor([0.0900, 0.2447, 0.6652], dtype=torch.float64)
tensor([1., 1., 1.], dtype=torch.float64)


### 손실 함수와 연계

In [14]:
import torch
import torch.nn as nn
import torch.optim as optim

# 간단한 다중 클래스 분류 모델 정의
class SimpleMultiClassModel(nn.Module):
    def __init__(self):
        super(SimpleMultiClassModel, self).__init__()
        self.fc = nn.Linear(5, 3) # fully connected

    def forward(self, x):
        return self.fc(x)
    

model = SimpleMultiClassModel()
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

# 데이터 생성
inputs = torch.randn(4, 5)
labels = torch.tensor([0, 2, 1, 0])

for _ in range(10):
    preds = model(inputs)           # 순전파
    loss = criterion(preds, labels) # 손실계산
    print(loss.item())
    
    optimizer.zero_grad()           # 기울기 초기화     이전단계에서 계산된 기울기를 0으로 초기화
    loss.backward()                 # 역전파           손실에 대한 역전파 수행 파라미터에 대한 기울기 계산
    optimizer.step()                # 가중치 업데이트   계산된 기울기를 사용하여 옵티마이저가 모델의 파라밈터 업뎃


1.1523725986480713
1.121687650680542
1.0915027856826782
1.0618436336517334
1.0327346324920654
1.0041998624801636
0.9762616753578186
0.9489403963088989
0.9222531914710999
0.8962143659591675
